# Generated by Django 5.2.4 on 2025-07-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('valet_price_per_day', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('car_wash_price', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('keep_key_price_per_day', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('max_price_per_day', models.DecimalField(decimal_places=2, default=60.0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='car_wash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='keep_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='valet',
            field=models.BooleanField(default=False),
        ),
    ]
