# Generated by Django 5.2.4 on 2025-07-14 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pricetable_parkingspot_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField(help_text='Preço acordado para este dia, arredondado para baixo, sem extras.')),
                ('valet', models.BooleanField(default=False)),
                ('car_wash', models.BooleanField(default=False)),
                ('keep_key', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.reservation')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('reservation', 'date')},
            },
        ),
    ]
