# Generated by Django 5.2.4 on 2025-07-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservationday'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationday',
            name='car_wash_price',
            field=models.IntegerField(default=0, help_text='Preço da lavagem para este dia (só no primeiro dia se aplicável).'),
        ),
        migrations.AddField(
            model_name='reservationday',
            name='keep_key_price',
            field=models.IntegerField(default=0, help_text='Preço de ficar com a chave para este dia.'),
        ),
        migrations.AddField(
            model_name='reservationday',
            name='valet_price',
            field=models.IntegerField(default=0, help_text='Preço do valet para este dia.'),
        ),
        migrations.AlterField(
            model_name='reservationday',
            name='price',
            field=models.IntegerField(help_text='Preço base acordado para este dia, arredondado para baixo.'),
        ),
    ]
