# Generated by Django 5.2.4 on 2025-07-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reservationday_car_wash_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='valet',
        ),
        migrations.RemoveField(
            model_name='reservationday',
            name='car_wash',
        ),
        migrations.RemoveField(
            model_name='reservationday',
            name='keep_key',
        ),
        migrations.RemoveField(
            model_name='reservationday',
            name='valet',
        ),
        migrations.RemoveField(
            model_name='reservationday',
            name='valet_price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='shuttle_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='shuttle_recolha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='valet_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='valet_recolha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationday',
            name='shuttle_entrega_price',
            field=models.IntegerField(default=0, help_text='Preço do shuttle entrega para este dia.'),
        ),
        migrations.AddField(
            model_name='reservationday',
            name='shuttle_recolha_price',
            field=models.IntegerField(default=0, help_text='Preço do shuttle recolha para este dia.'),
        ),
        migrations.AddField(
            model_name='reservationday',
            name='valet_entrega_price',
            field=models.IntegerField(default=0, help_text='Preço do valet entrega para este dia.'),
        ),
        migrations.AddField(
            model_name='reservationday',
            name='valet_recolha_price',
            field=models.IntegerField(default=0, help_text='Preço do valet recolha para este dia.'),
        ),
        migrations.AlterField(
            model_name='reservationday',
            name='car_wash_price',
            field=models.IntegerField(default=0, help_text='Preço da lavagem para este dia (só no dia antes da recolha se aplicável).'),
        ),
    ]
